// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StepCounter.Infrastructure.PersistenceContext;

#nullable disable

namespace StepCounter.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241028110208_Migration1")]
    partial class Migration1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0-rc.2.24474.1");

            modelBuilder.Entity("StepCounter.Core.Model.Counter.Counter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("StepCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Counters");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2e76c467-716b-49ea-adc9-444ea003b115"),
                            StepCount = 0
                        });
                });

            modelBuilder.Entity("StepCounter.Core.Model.GlobalScore.GlobalScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CounterId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GlobalScores");

                    b.HasData(
                        new
                        {
                            Id = new Guid("46f7af77-91ce-4374-8368-b96fe18d09ea"),
                            CounterId = new Guid("2e76c467-716b-49ea-adc9-444ea003b115")
                        });
                });

            modelBuilder.Entity("StepCounter.Core.Model.Team.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("MembersCountersIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TeamCounterId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });
#pragma warning restore 612, 618
        }
    }
}
